--- 
- 
  become: true
  hosts: nginx
  name: "nginx install & start services"
  tasks: 
    - 
      name: "install nginx"
      yum: 
        name: nginx
        state: present
    - 
      copy: 
        dest: /usr/share/nginx/html/
        src: ./playbooks/index.html
      name: "Copy file with owner and permissions"
    - 
      name: "start nginx"
      service: 
        name: nginx
        state: started
        enabled: yes

